version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=app
      - PMA_PASSWORD=secret
    ports:
      - "81:80"
    volumes:
      - /sessions
    networks:
      - app-network
  
  app:
    image: ghcr.io/kma-custom-nextcloud/nextcloud-server:22
    restart: always
    ports:
      - 8080:80
    volumes:
      - .data/server:/var/www/html
    environment:
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_HOST=mysql
    networks:
      - app-network

  code:
    image: collabora/code:latest
    cap_add:      
      - MKNOD 
    restart: always    
    ports:      
      - "9980:9980"    
    environment:      
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=false"      
      - "domain=192.168.0.101"
  
  cred:
    image: nopain1210/nc-cred:latest
    restart: always
    ports:
      - "13000:3000"
    
networks:
  app-network:
    driver: bridge
      